### ISSUE TITLE
SOCK_DGRAM vs SOCK_RAW?

### ISSUE THREAD

**Issue by gosh24** [atlarge-research/cn-lab-student#33]
I have found that using SOCK_DGRAM actually isolates the payload from the UDP header and the OS automatically discards packets that have a bad checksum. I am seeing significant progress by using SOCK_RAW as I can inspect the packet more deeply, however, when I attempt to test it in codegrade, the "did not start or connected to wrong port" error shows up. The program needs to be run with administrator privileges in order to use the raw socket.

Your server is not configured to send any CRC, checksum or any error detection mechanism in the payload itself, so I think it is impossible to do anything without actually accessing the UDP header.

Could you please configure the codegrade testing environment for this assignment to run the file with administrator privileges?

https://stackoverflow.com/questions/58552869/checksum-checking-in-udp-using-udp-socket

gbv500

**Comment by fzovpec** [comment]
Hello,

You have done a very good research on the topic; however, I believe there is a misunderstanding of the assignment. You should implement your own error detection/correction technique rather than using the existing UDP mechanisms. The way it works is you send a message to a server, server sometimes modifies it simulating network unreliability and resends the message to the destination user. Your message in Unreliable Chat Client could look as "[MSG][ERROR CORRECTION/DETECTION]". This error detection / correction technique you should calculate on your own (for example it can be CRC) and you probably would want to put it in your data so that upon receiving a message a receiver can check the code against the received message.

Hope this makes sense but if it does not please come during one of the labs and the team of TAs will be happy to help you. I wish you a good academic luck for this upcoming week!
