### ISSUE TITLE
UDP server bug

### ISSUE THREAD

**Issue by marwandr** [atlarge-research/cn-lab-student#81]
![image](https://github.com/atlarge-research/cn-lab-student/assets/156030182/2a90f77c-7d99-4717-965a-dd0d0ac1bec2)
```
Instead of sending according to the chat protocol:
VALUE <name> <value> (<upper>)\n

It is only sending:
VALUE<value> (<upper>)\n

**Comment by fzovpec** [comment]
@TheCodingDutchman no, he is talking about the remote server, they have slightly different implementation due to the different handling of unreliability arguments. @marwandr, the issue should be fixed now, thanks for letting me know. Just like with the other PR, ping me with your VUNetID so I can assign points

**Comment by marwandr** [comment]
@fzovpec thank you, my vunetID is mam226
